version: '3.7'

services:
  db:
   container_name: postgres
   image: postgres:15.2
   restart: always
   environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   ports:
     - "${POSTGRES_PORT}:${POSTGRES_PORT}"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   networks: 
      teastream-backend: {}

volumes:
  postgres_data:

networks: 
  teastream-backend: